### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by studio1902** [edalzell/statamic-download#1]
Note: updated this post a few times. You can ignore previous edits.

Container:
`path: secured-downloads
title: 'Beveiligde downloads'`

Data:
`secured_download: 'secured-downloads::cursusmateriaal-wiscv-november-2019.zip'`

Template:
`<a href="{{ download :file='secured_download' container='secured-downloads' }}">`

Generated link:
`/!/Download/get?file=secured-downloads::cursusmateriaal-ids-2-september-2019.zip&container=secured-downloads`

This gives me a file not found error. 

When I leave out the container parameter I get an error page:
`ErrorException in Collection.php line 1032:
array_key_exists(): The first argument should be either a string or an integer`

**Comment by studio1902** [comment]
Noteworthy: when saving the addons settings an error get's outputted to the Statamic logs:

`[2020-01-07 20:19:32] dev.ERROR: ErrorException: Trying to access array offset on value of type int in /Users/robdekort/Repositories/dekinderacademie.com/statamic/vendor/symfony/console/Input/ArrayInput.php:121
Stack trace:
#0 /Users/robdekort/Repositories/dekinderacademie.com/statamic/vendor/symfony/console/Input/ArrayInput.php(121): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Trying to acces...', '/Users/robdekor...', 121, Array)
#1 /Users/robdekort/Repositories/dekinderacademie.com/statamic/vendor/symfony/console/Input/Input.php(51): Symfony\Component\Console\Input\ArrayInput->parse()
#2 /Users/robdekort/Repositories/dekinderacademie.com/statamic/vendor/symfony/console/Command/Command.php(197): Symfony\Component\Console\Input\Input->bind(Object(Symfony\Component\Console\Input\InputDefinition))
#3 /Users/robdekort/Repositories/dekinderacademie.com/statamic/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#4 /Users/robdekort/Repositories/dekinderacademie.com/statamic/vendor/symfony/console/Application.php(840): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#5 /Users/robdekort/Repositories/dekinderacademie.com/statamic/vendor/symfony/console/Application.php(190): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Cache\Console\ClearCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#6 /Users/robdekort/Repositories/dekinderacademie.com/statamic/vendor/symfony/console/Application.php(114): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#7 /Users/robdekort/Repositories/dekinderacademie.com/statamic/vendor/laravel/framework/src/Illuminate/Console/Application.php(64): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#8 /Users/robdekort/Repositories/dekinderacademie.com/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(159): Illuminate\Console\Application->call('cache:clear', Object(Illuminate\Support\Collection))
#9 /Users/robdekort/Repositories/dekinderacademie.com/statamic/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(215): Illuminate\Foundation\Console\Kernel->call('cache:clear')
#10 /Users/robdekort/Repositories/dekinderacademie.com/statamic/core/API/Cache.php(72): Illuminate\Support\Facades\Facade::__callStatic('call', Array)
#11 /Users/robdekort/Repositories/dekinderacademie.com/statamic/core/Http/Controllers/AddonsController.php(140): Statamic\API\Cache::clear()
#12 [internal function]: Statamic\Http\Controllers\AddonsController->saveSettings(Object(Illuminate\Http\Request), Object(Statamic\Extend\Addon))
#13 /Users/robdekort/Repositories/dekinderacademie.com/statamic/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(256): call_user_func_array(Array, Array)
#14 /Users/robdekort/Repositories/dekinderacademie.com/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(164): Illuminate\Routing\Controller->callAction('saveSettings', Array)
#15 /Users/robdekort/Repositories/dekinderacademie.com/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(112): Illuminate\Routing\ControllerDispatcher->call(Object(Statamic\Http\Controllers\AddonsController), Object(Illuminate\Routing\Route), 'saveSettings')
#16 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#17 /Users/robdekort/Repositories/dekinderacademie.com/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#18 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 /Users/robdekort/Repositories/dekinderacademie.com/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#20 /Users/robdekort/Repositories/dekinderacademie.com/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#21 /Users/robdekort/Repositories/dekinderacademie.com/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(68): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Statamic\Http\Controllers\AddonsController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'saveSettings')
#22 /Users/robdekort/Repositories/dekinderacademie.com/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Statamic\\Http\\C...', 'saveSettings')
#23 /Users/robdekort/Repositories/dekinderacademie.com/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#24 /Users/robdekort/Repositories/dekinderacademie.com/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(708): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#25 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#26 /Users/robdekort/Repositories/dekinderacademie.com/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#27 /Users/robdekort/Repositories/dekinderacademie.com/statamic/core/Http/Middleware/CP/Configurable.php(23): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 [internal function]: Statamic\Http\Middleware\CP\Configurable->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /Users/robdekort/Repositories/dekinderacademie.com/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#30 /Users/robdekort/Repositories/dekinderacademie.com/statamic/core/Http/Middleware/CP/Authenticate.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 [internal function]: Statamic\Http\Middleware\CP\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /Users/robdekort/Repositories/dekinderacademie.com/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#33 /Users/robdekort/Repositories/dekinderacademie.com/statamic/core/Http/Middleware/Outpost.php(48): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 [internal function]: Statamic\Http\Middleware\Outpost->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /Users/robdekort/Repositories/dekinderacademie.com/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#36 /Users/robdekort/Repositories/dekinderacademie.com/statamic/core/Http/Middleware/CP/Localize.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 [internal function]: Statamic\Http\Middleware\CP\Localize->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 /Users/robdekort/Repositories/dekinderacademie.com/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#39 /Users/robdekort/Repositories/dekinderacademie.com/statamic/core/Http/Middleware/CP/DefaultLocale.php(28): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 [internal function]: Statamic\Http\Middleware\CP\DefaultLocale->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /Users/robdekort/Repositories/dekinderacademie.com/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#42 /Users/robdekort/Repositories/dekinderacademie.com/statamic/core/Http/Middleware/CP/AddHeaders.php(19): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 [internal function]: Statamic\Http\Middleware\CP\AddHeaders->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 /Users/robdekort/Repositories/dekinderacademie.com/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#45 /Users/robdekort/Repositories/dekinderacademie.com/statamic/core/Http/Middleware/CpEnabled.php(23): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 [internal function]: Statamic\Http\Middleware\CpEnabled->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 /Users/robdekort/Repositories/dekinderacademie.com/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#48 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 /Users/robdekort/Repositories/dekinderacademie.com/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#50 /Users/robdekort/Repositories/dekinderacademie.com/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(710): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#51 /Users/robdekort/Repositories/dekinderacademie.com/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(674): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#52 /Users/robdekort/Repositories/dekinderacademie.com/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#53 /Users/robdekort/Repositories/dekinderacademie.com/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(236): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#54 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#55 /Users/robdekort/Repositories/dekinderacademie.com/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#56 /Users/robdekort/Repositories/dekinderacademie.com/statamic/vendor/barryvdh/laravel-debugbar/src/Middleware/Debugbar.php(51): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#57 [internal function]: Barryvdh\Debugbar\Middleware\Debugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 /Users/robdekort/Repositories/dekinderacademie.com/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#59 /Users/robdekort/Repositories/dekinderacademie.com/statamic/core/Http/Middleware/TransformsRequest.php(31): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#60 [internal function]: Statamic\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#61 /Users/robdekort/Repositories/dekinderacademie.com/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#62 /Users/robdekort/Repositories/dekinderacademie.com/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#63 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#64 /Users/robdekort/Repositories/dekinderacademie.com/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#65 /Users/robdekort/Repositories/dekinderacademie.com/statamic/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#66 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#67 /Users/robdekort/Repositories/dekinderacademie.com/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#68 /Users/robdekort/Repositories/dekinderacademie.com/statamic/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#69 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#70 /Users/robdekort/Repositories/dekinderacademie.com/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#71 /Users/robdekort/Repositories/dekinderacademie.com/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#72 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#73 /Users/robdekort/Repositories/dekinderacademie.com/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#74 /Users/robdekort/Repositories/dekinderacademie.com/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#75 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#76 /Users/robdekort/Repositories/dekinderacademie.com/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#77 /Users/robdekort/Repositories/dekinderacademie.com/statamic/core/StaticCaching/Middleware/Retrieve.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#78 [internal function]: Statamic\StaticCaching\Middleware\Retrieve->handle(Object(Illuminate\Http\Request), Object(Closure))
#79 /Users/robdekort/Repositories/dekinderacademie.com/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#80 /Users/robdekort/Repositories/dekinderacademie.com/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#81 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#82 /Users/robdekort/Repositories/dekinderacademie.com/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#83 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#84 /Users/robdekort/Repositories/dekinderacademie.com/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#85 /Users/robdekort/Repositories/dekinderacademie.com/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#86 /Users/robdekort/Repositories/dekinderacademie.com/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#87 /Users/robdekort/Repositories/dekinderacademie.com/public/index.php(155): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#88 /Users/robdekort/.composer/vendor/laravel/valet/server.php(158): require('/Users/robdekor...')
#89 {main}  
`

**Comment by studio1902** [comment]
Update. I wasn't following the docs explicitly it seems. If I do the following which seems correct, I don't get an error, but I don't get a download either. The page just refreshes.

Data: 
`secured_download: 'cursusmateriaal-wiscv-november-2019.zip'`

Template: 
`<a href="{{ download :file='secured_download' container='secured-downloads' }}">Download</a>`

Rendered HTML:
`<a href="/!/Download/get?file=cursusmateriaal-wiscv-november-2019.zip&amp;container=secured-downloads">Download</a>`
